import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: "Kartik",
      email: "kartik.randeria@xaviers.edu.in",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Abhinash Yadav",
      email: "abhinash.yadav@xaviers.edu.in",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Mohd. Zaffar Sayyed",
      email: "mohd.zaffer.sayyed@xaviers.edu.in",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "C#",
      category: "Programming",
      image: "/images/p1.jpg",
      price: 750,
      countInStock: 10,
      author: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "C-SHARP (C#) is a general-purpose, multi-paradigm programming language developed by Microsoft that runs on the . NET framework. C# is widely used for building mobile applications, games, and windows applications.\nC-SHARP (C#) is a general-purpose, multi-paradigm programming language developed by Microsoft that runs on the . NET framework. C# is widely used for building mobile applications, games, and windows applications.\nC-SHARP (C#) is a general-purpose, multi-paradigm programming language developed by Microsoft that runs on the . NET framework. C# is widely used for building mobile applications, games, and windows applications.",
    },
    {
      name: "Python Programming",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 20,
      author: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 220,
      countInStock: 0,
      author: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 78,
      countInStock: 15,
      author: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 65,
      countInStock: 5,
      author: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 139,
      countInStock: 12,
      author: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;